### ISSUE TITLE
Test suite build failure w/ C preprocessor

### ISSUE THREAD

**Issue by DanBurton** [aycanirican/hweblib#3]
Build failure with GHC 8.2.1 as seen on the Stackage build server.

```
1: ./Setup build (pending: 1312, failures: 21)

Building test suite 'testsuite' for hweblib-0.6.3..

src/Network/Parser/Mime.hs:23:0: error:
     error: missing binary operator before token "("
     #if MIN_VERSION_text(0,11,3)
     ^
   |
23 | #if MIN_VERSION_text(0,11,3)
   | ^
`gcc' failed in phase `C pre-processor'. (Exit code: 1)
```

**Comment by aycanirican** [comment]
@DanBurton I finally found some time to cleanup and improve the library. Thank you for reporting it, and sorry for the big delay. I just added `Message.hs` which is a more clean interface for working on message type. `Mime.hs` will be removed as soon as i cleanup and write tests for `Message.hs`.

Thank you.

**Comment by aycanirican** [comment]
BTW, I just added 3 different versions (8.2, 8.4 and 8.6) of ghc to travis config.
